# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1209127bbb32239f6c22364e204a26b9fff26bfe34638936346b6dccbf4c9750ef35d176c0c6d8d4cf605971d7ffc728828362eaf8155d2ba1a238191a5f08e7

test:
  secret_key_base: 6d8f1887c784711b91fb04ec32e733a315521b13b6b3a9a48ab3e2463485a46195fd8dc6b2ec32613ddac23e6aee20312be506ca2461611b7529cacf0afcf47b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
